[package]
name = "remindee-bot"
version = "0.1.10"
authors = ["Nikolai Oplachko <magnickolas@gmail.com>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Reminder bot for Telegram without bullshit"
homepage = "https://oplachko.com"
repository = "https://github.com/magnickolas/remindee-bot"
readme = "README.md"
keywords = ["bot","reminder", "cron", "telegram-bot", "reminders"]
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
chrono = "0.4.19"
chrono-tz = "0.6.0"
cron-parser = "0.7.9"
directories = "4.0.1"
lazy_static = "1.4.0"
regex = "1.5.4"
rusqlite = { version = "0.26.0", features = ["chrono", "bundled"] }
teloxide = "0.5.2"
teloxide-macros = "0.4.1"
openssl = { version = "0.10.36", features = ["vendored"] }

log = "0.4.14"
pretty_env_logger = "0.4.0"

tokio = { version = "1.12.0", features = ["rt-multi-thread", "macros"] }
itertools = "0.10.1"
